{% set name = "sphinx-jupyterbook-latex" %}
{% set pip_name = name.replace("-", "_") %}
{% set version = "0.4.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz
  sha256: dbc997ae9ee1fd51277c6ad66e93c9cad2a6158fa02b304621e703ea6d3bae98

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sphinx >=3,<4
    - myst-nb >=0.11,<0.13
    - sqlalchemy >=1.3.12,<1.4
    - importlib_resources

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - sphinx_jupyterbook_latex
    - sphinx_jupyterbook_latex.theme


about:
  home: https://github.com/executablebooks/sphinx-jupyterbook-latex
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    Sphinx-jupyterbook-latex: Supporting LaTeX infrastructure for Jupyter Book
  dev_url: https://github.com/executablebooks/sphinx-jupyterbook-latex


extra:
  recipe-maintainers:
    - AakashGfude
    - conda-forge/jupyter-book
    - chrisjsewell
    - mmcky
