{% set name = "sphinx-jupyterbook-latex" %}
{% set pip_name = name.replace("-", "_") %}
{% set version = "0.4.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ pip_name }}/{{ pip_name }}-{{ version }}.tar.gz
  sha256: b169ab271f512f45cea93587bd573f32f513eb744a680908874a2a60c62f6884

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sphinx >=3,<5
    - importlib_resources
  run_constrained:
    - myst-nb >=0.13,<0.14

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - sphinx_jupyterbook_latex
    - sphinx_jupyterbook_latex.theme


about:
  home: https://github.com/executablebooks/sphinx-jupyterbook-latex
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    Sphinx-jupyterbook-latex: Supporting LaTeX infrastructure for Jupyter Book
  dev_url: https://github.com/executablebooks/sphinx-jupyterbook-latex


extra:
  recipe-maintainers:
    - AakashGfude
    - conda-forge/jupyter-book
    - chrisjsewell
    - mmcky
