{% set version = "1.0.0" %}

package:
  name: sphinx-jupyterbook-latex
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sphinx_jupyterbook_latex/sphinx_jupyterbook_latex-{{ version }}.tar.gz
  sha256: f54c6674c13f1616f9a93443e98b9b5353f9fdda8e39b6ec552ccf0b3e5ffb62

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.9
    - flit-core >=3.2,<4
  run:
    - packaging
    - python >=3.9
    - sphinx >=5
  run_constrained:
    - myst-nb >=1.0.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - sphinx_jupyterbook_latex
    - sphinx_jupyterbook_latex.theme

about:
  home: https://github.com/executablebooks/sphinx-jupyterbook-latex
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Latex specific features for jupyter book

extra:
  recipe-maintainers:
    - AakashGfude
    - conda-forge/jupyter-book
    - chrisjsewell
    - mmcky
